<?php $this->headScript()->appendFile($this->assetUrl('js/config.js', 'KohaImport'));?>

<?php echo $this->pageTitle($this->translate('Import from Koha')); ?>

<?php $this->trigger('view.index.before'); ?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<?php $this->trigger('view.index.form.before'); ?>
<?php echo $this->formCollection($form); ?>
<?php $this->trigger('view.index.form.after'); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Next'); ?></button>
</div>

<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.index.after'); ?>
